sonar.projectKey=SASINDUMX_VehicalTrackingApp
sonar.organization=sasindumx
sonar.projectName=VehicalTrackingApp
sonar.host.url=https://sonarcloud.io

# Source code settings
sonar.sources=src,App.tsx,index.js,scripts
sonar.exclusions=node_modules/**,dist/**,assets/**,.expo/**,public/**
sonar.javascript.environments=browser,react-native,node
